# Generated by Django 4.2.7 on 2023-12-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=200)),
                ('calificacion', models.CharField(choices=[('1', '1 ESTRELLA'), ('2', '2 ESTRELLAS'), ('3', '3 ESTRELLAS'), ('4', '4 ESTRELLAS'), ('5', '5 ESTRELLAS')], max_length=1)),
                ('resenia', models.CharField(max_length=200)),
                ('fecha', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'Reseña de clientes',
            },
        ),
    ]
