# Generated by Django 5.0 on 2023-12-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenia_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenia',
            name='calificacion',
            field=models.CharField(choices=[('⭐', '1 ESTRELLA'), ('⭐⭐', '2 ESTRELLAS'), ('⭐⭐⭐', '3 ESTRELLAS'), ('⭐⭐⭐⭐', '4 ESTRELLAS'), ('⭐⭐⭐⭐⭐', '5 ESTRELLAS')], max_length=5),
        ),
    ]
